SB-22541 : CourseBatch date changes updation
project-sunbird/sunbird-course-service pull request #361
Opened 2021-05-03 15:08 UTC by neha0305verma

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions: Java-11, play2-2.7.2, scala-2.11, redis-5.0.3
* Hardware versions: 2 CPU / 4GB RAM

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2021-05-04 05:56 UTC, PradyumnaNagendra requested changes

2021-05-04 05:56 UTC, PradyumnaNagendra commented on course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
> +  public static final List<String> CHANGE_IN_DATE_FORMAT_ALL = new ArrayList<String>() {{add("startDate"); add("endDate"); add("enrollmentEndDate"); add("createdDate"); add("updatedDate");}};
you can use Arrays.asList

2021-05-04 05:56 UTC, PradyumnaNagendra commented on course-mw/sunbird-util/sunbird-platform-core/common-util/src/main/java/org/sunbird/common/models/util/JsonKey.java
> +  public static final List<String> CHANGE_IN_DATE_FORMAT_ALL = new ArrayList<String>() {{add("startDate"); add("endDate"); add("enrollmentEndDate"); add("createdDate"); add("updatedDate");}};
do the same for this also 
`public static final List<String> SET_END_OF_DAY = new ArrayList<String>() {{add("endDate"); ad("enrollmentEndDate");}};`

2021-05-04 08:04 UTC, PradyumnaNagendra approved these changes

2021-05-04 10:07 UTC, maheshkumargangula requested changes

2021-05-04 10:07 UTC, maheshkumargangula commented on course-mw/course-actors-common/src/main/java/org/sunbird/learner/util/CourseBatchUtil.java
> +  private static final SimpleDateFormat DATE_FORMAT_SIMPLE = new SimpleDateFormat("yyyy-MM-dd");
SimpleDateFormat - Concurrency will create issues for the format. Please use it as local variable.

2021-05-04 11:56 UTC, PradyumnaNagendra requested changes

2021-05-04 11:56 UTC, PradyumnaNagendra commented on course-mw/course-actors/src/main/java/org/sunbird/learner/actors/coursebatch/CourseBatchManagementActor.java
> +            if (MapUtils.isEmpty(result) || (result.containsKey(JsonKey.IS_DELETED) && (Boolean) result.get(JsonKey.IS_DELETED))) {
result.get(JsonKey.IS_DELETED, false)

2021-05-06 08:35 UTC, PradyumnaNagendra approved these changes

2021-05-07 07:12 UTC, maheshkumargangula approved these changes

2021-05-07 07:12 UTC, merged